version: "3"

services:
  conditionize:
    container_name: conditionize
    build:
      context: ./
      dockerfile: Dockerfile.dev

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    ports:
      - 3000:3000
